print("-------------------------------------------------------------")
print("|              EQUITY BANK                                  |")
print("|              CBD  BRANCH                                  |")
print("|             20TH SEP 2020                                 |")
print("|FIRST NAME : DAVID                                         |")
print("|SECOND NAME : GITHEHU                                      |")
print("|ACC NO : 8081235765                                        |")
print("|ACC BALANCE : KSH 9000000000                               |")
print("-------------------------------------------------------------")
