#creating a triangle
print("                     *                        ")
print("                    * *                       ")
print("                   * * *                      ")
print("                  * * * *                     ")
print("                 * * * * *                    ")
print("                * * * * * *                   ")
print("               * * * * * * *                  ")
print("              * * * * * * * *                 ")
print("             * * * * * * * * *                ")