#creating a diamond
print("                           *                              ")
print("                          * *                             ")
print("                         * * *                            ")
print("                        * * * *                           ")
print("                       * * * * *                          ")
print("                        * * * *                           ")
print("                         * * *                            ")
print("                          * *                             ")
print("                           *                              ")