name = input("what is your name")
print("My name is",name)
f_name = ("what is your first name ?")
s_name = input("What is your second name")
print("My first name is",f_name)
print("My second name is",s_name)
f_num = input("Enter first number : ")
s_num = input("Enter the second number : ")
#convert the string to intengers
sum_num = f_num + s_num
print("The sum of the number is :",sum_num)
sum_num = int(f_num) + int(s_num)
print("The sum of number is :",sum_num)
diff_num = int(f_num) - int(s_num)
quot_num = int(f_num) / int(s_num)
prod_num = int(f_num) * int(s_num)
print("The different of the number is :",diff_num)
print("The quotient of the number is :",quot_num)
print("The product of the number is :",prod_num)